### ISSUE TITLE
Documentation build_api_docs.py

### ISSUE THREAD

**Issue by eileenrmartin** [DASDAE/dascore#87]
After installing quarto, I had an error when trying to build the api docs.

OS: Mac 11.6.5

(dascore) eileenmartin@csm-wl-dhcp-197-90 dascore % where quarto
/usr/local/bin/quarto
(dascore) eileenmartin@csm-wl-dhcp-197-90 dascore % ls    
dascore			environment.yml		scripts
dascore.egg-info	pyproject.toml		setup.cfg
docs			readme.md		tests
(dascore) eileenmartin@csm-wl-dhcp-197-90 dascore % cd scripts
(dascore) eileenmartin@csm-wl-dhcp-197-90 scripts % ls
_index_api.py		_render_api.py		_templates		build_api_docs.py
(dascore) eileenmartin@csm-wl-dhcp-197-90 scripts % python build_api_docs.py
Traceback (most recent call last):
  File "/Users/eileenmartin/dascore/scripts/build_api_docs.py", line 10, in <module>
    data_dict = parse_project(dascore)
  File "/Users/eileenmartin/dascore/scripts/_index_api.py", line 196, in parse_project
    traverse(obj, data_dict, base_path)
  File "/Users/eileenmartin/dascore/scripts/_index_api.py", line 171, in traverse
    traverse(mod, data_dict, base_path)
  File "/Users/eileenmartin/dascore/scripts/_index_api.py", line 171, in traverse
    traverse(mod, data_dict, base_path)
  File "/Users/eileenmartin/dascore/scripts/_index_api.py", line 169, in traverse
    data_dict[obj_id] = get_data(obj, key, base_path, parent_is_class)
  File "/Users/eileenmartin/dascore/scripts/_index_api.py", line 136, in get_data
    data = extract_data(obj, parent_is_class)
  File "/Users/eileenmartin/dascore/scripts/_index_api.py", line 111, in extract_data
    data["short_description"] = docstr.split("\n")[0]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by eileenrmartin** [comment]
Tried again and it works? It's magically suspicious, but I'll close this out for now.
